name: "Question"
description: "Ask a general question about anything"
title: "Summarize your question"
labels: ["status: evaluating", "type: question"]
assignees:
  - iceeburr
body:
  - type: markdown
    attributes:
      value: Got a question? Let's answer it!
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please enter an explicit description of your question"
      placeholder: "Short and explicit description of your question..."
      render: markdown
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: "Screenshots & Videos"
      description: "If applicable, add any media files to help explain your question"
      placeholder: "https://imgur.com/a/abcdefg"
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional Information"
      description: "Include any additional information about the question"
    validations:
      required: false
