name: "Close Stale Issue & PRs"
on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.1.0
        with:
          stale-issue-message: "This issue has been put on stale due to inactivity"
          close-issue-message: "This issue has been closed due to inactivity"
          stale-pr-message: "This PR has been put on stale due to inactivity"
          close-pr-message: "This PR has been closed due to inactivity"
          stale-issue-label: "status: stale"
          stale-pr-label: "status: stale"
          labels-to-remove-when-unstale: "status: stale"
          exempt-issue-labels: "no-stale, priority: critical"
          exempt-pr-labels: "no-stale, priority: critical"
          days-before-stale: 14
          days-before-close: 7
          close-issue-reason: "not_planned"
